apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: oci-private-apps
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - kind: Gateway
      group: gateway.networking.k8s.io
      name: oci-private-apps
  proxyProtocol:
    optional: false